theme: jekyll-theme-cayman

title: Plye
description: The main destination for all information relating to Plye.
show_downloads: true

permalink: pretty

collections:
  info:
    output: true
    permalink: /info/:title/
  develop:
    output: true
    permalink: /development/:title/